#Questions

#What line of code do you need to change the Rails Welcome Aboard page? In what file do we put this code?

config/routes.rb/:
   
   root "welcome#index"


#What paths are generated by the following code: resources :articles ?





What line of code do you need to fix the following error: ActiveModel::ForbiddenAttributesError ? Which file? Why?





Provide one example of a refactoring techinque using partials. Include the partial file name, the code inside the partial, and the code used to display that partial.

